-- Regenerates db/security-model.sql from the live database.
--
-- The database is managed out of band (changes are applied directly in
-- Supabase; there are no migrations in this repo). That left the layer that
-- actually enforces the app's central privacy promise — that household
-- membership grants no access to any child's health records — impossible to
-- review or diff. This dump exists to close that gap: run it, save the output
-- over db/security-model.sql, and commit. A policy that changes without an
-- accompanying commit then shows up as a diff.
--
-- Read-only. Running this cannot alter the database.
--
--   psql "$SUPABASE_DB_URL" -At -f db/dump-security-model.sql > db/security-model.sql
--
-- (or paste it into the Supabase SQL editor and save the single text column)

with header as (
  select format(
    E'-- SickleStrong — database security model (GENERATED SNAPSHOT, DO NOT APPLY)\n' ||
    E'--\n' ||
    E'-- Generated by db/dump-security-model.sql on %s UTC.\n' ||
    E'-- This is a REVIEW ARTIFACT, not a migration. The live database is the\n' ||
    E'-- source of truth; this file exists so the access rules can be read,\n' ||
    E'-- diffed, and code-reviewed alongside the frontend that depends on them.\n' ||
    E'-- Do not run it against a database.\n' ||
    E'--\n' ||
    E'-- The promise these rules enforce: every table holding a child''s health\n' ||
    E'-- data is scoped by child_access (via accessible_child_ids /\n' ||
    E'-- full_access_child_ids / report_access_child_ids), never by family_id.\n' ||
    E'-- Being in a household is not access to a child.\n',
    to_char(now() at time zone 'utc', 'YYYY-MM-DD HH24:MI')) as line,
    '' as t, -1 as ord, 0 as sect
),
funcs as (
  select E'\n\n-- ============================================================\n' ||
         E'-- ACCESS HELPERS — every policy below resolves through these\n' ||
         E'-- ============================================================\n' as line,
         '' as t, -1 as ord, 1 as sect
  union all
  select pg_get_functiondef(p.oid), p.proname, 0, 1
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.proname in ('accessible_child_ids','full_access_child_ids',
                      'report_access_child_ids','is_parent_of_child')
),
rpcs as (
  select E'\n\n-- ============================================================\n' ||
         E'-- SECURITY DEFINER RPCs — the only way access is ever granted\n' ||
         E'-- ============================================================\n' as line,
         '' as t, -1 as ord, 2 as sect
  union all
  select pg_get_functiondef(p.oid), p.proname, 0, 2
  from pg_proc p join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public'
    and p.proname in ('provision_current_user','redeem_child_invite',
                      'generate_child_invite','cancel_child_invite',
                      'lookup_family_by_code','switch_household',
                      'set_child_active_status','delete_child_permanently',
                      'grant_owner_child_access','prevent_last_parent_removal')
),
pols as (
  select E'\n\n-- ============================================================\n' ||
         E'-- ROW LEVEL SECURITY\n' ||
         E'-- ============================================================\n' as line,
         '' as t, -1 as ord, 3 as sect
  union all
  select format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', c.relname),
         c.relname, 0, 3
  from pg_class c join pg_namespace n on n.oid = c.relnamespace
  where n.nspname = 'public' and c.relkind = 'r' and c.relrowsecurity
  union all
  select format(E'CREATE POLICY %I ON public.%I\n  FOR %s TO %s%s%s;',
           p.policyname, p.tablename, p.cmd, array_to_string(p.roles, ', '),
           case when p.qual is null then '' else E'\n  USING (' || p.qual || ')' end,
           case when p.with_check is null then '' else E'\n  WITH CHECK (' || p.with_check || ')' end),
         p.tablename, 1, 3
  from pg_policies p
  where p.schemaname = 'public'
),
all_lines as (
  select * from header
  union all select * from funcs
  union all select * from rpcs
  union all select * from pols
)
select string_agg(line, E'\n' order by sect, t, ord, line) from all_lines;
