-- SickleStrong — database security model (GENERATED SNAPSHOT, DO NOT APPLY)
--
-- Generated by db/dump-security-model.sql on 2026-08-25 13:32 UTC.
-- This is a REVIEW ARTIFACT, not a migration. The live database is the
-- source of truth; this file exists so the access rules can be read,
-- diffed, and code-reviewed alongside the frontend that depends on them.
-- Do not run it against a database.
--
-- The promise these rules enforce: every table holding a child's health
-- data is scoped by child_access (via accessible_child_ids /
-- full_access_child_ids / report_access_child_ids), never by family_id.
-- Being in a household is not access to a child.


-- ============================================================
-- ACCESS HELPERS — every policy below resolves through these
-- ============================================================

CREATE OR REPLACE FUNCTION public.accessible_child_ids()
 RETURNS SETOF uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT child_id FROM public.child_access WHERE auth_id = auth.uid();
$function$

CREATE OR REPLACE FUNCTION public.full_access_child_ids()
 RETURNS SETOF uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT child_id FROM public.child_access WHERE auth_id = auth.uid() AND permission = 'full';
$function$

CREATE OR REPLACE FUNCTION public.is_parent_of_child(p_child_id uuid)
 RETURNS boolean
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT EXISTS (
    SELECT 1 FROM public.child_access
    WHERE child_id = p_child_id AND auth_id = auth.uid() AND circle_role = 'parent'
  );
$function$

CREATE OR REPLACE FUNCTION public.report_access_child_ids()
 RETURNS SETOF uuid
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT child_id FROM public.child_access WHERE auth_id = auth.uid() AND permission IN ('report','full');
$function$


-- ============================================================
-- SECURITY DEFINER RPCs — the only way access is ever granted
-- ============================================================

CREATE OR REPLACE FUNCTION public.cancel_child_invite(p_invite_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_child_id uuid;
BEGIN
  SELECT child_id INTO v_child_id FROM public.child_invites WHERE id = p_invite_id;
  IF v_child_id IS NULL THEN
    RAISE EXCEPTION 'INVITE_NOT_FOUND';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.child_access ca
    WHERE ca.child_id = v_child_id AND ca.auth_id = auth.uid() AND ca.circle_role = 'parent'
  ) THEN
    RAISE EXCEPTION 'NOT_A_PARENT_FOR_THIS_CHILD';
  END IF;

  UPDATE public.child_invites SET revoked_at = now()
  WHERE id = p_invite_id AND revoked_at IS NULL;
END;
$function$

CREATE OR REPLACE FUNCTION public.delete_child_permanently(p_child_id uuid)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.child_access ca
    WHERE ca.child_id = p_child_id AND ca.auth_id = auth.uid() AND ca.circle_role = 'parent'
  ) THEN
    RAISE EXCEPTION 'NOT_A_PARENT_FOR_THIS_CHILD';
  END IF;

  ALTER TABLE public.child_access DISABLE TRIGGER child_access_prevent_last_parent;
  DELETE FROM public.contacts WHERE child_id = p_child_id;
  DELETE FROM public.medication_logs WHERE child_id = p_child_id;
  DELETE FROM public.children WHERE id = p_child_id;
  ALTER TABLE public.child_access ENABLE TRIGGER child_access_prevent_last_parent;
END;
$function$

CREATE OR REPLACE FUNCTION public.generate_child_invite(p_child_id uuid, p_permission text, p_circle_role text DEFAULT 'caregiver'::text)
 RETURNS TABLE(out_code text, out_expires_at timestamp with time zone)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid  uuid := auth.uid();
  v_code text;
  i      int;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'NOT_AUTHENTICATED';
  END IF;

  IF p_permission NOT IN ('full','report','view') THEN
    RAISE EXCEPTION 'INVALID_PERMISSION';
  END IF;
  IF p_circle_role NOT IN ('parent','caregiver') THEN
    RAISE EXCEPTION 'INVALID_CIRCLE_ROLE';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.child_access ca
    WHERE ca.child_id = p_child_id AND ca.auth_id = v_uid AND ca.circle_role = 'parent'
  ) THEN
    RAISE EXCEPTION 'NOT_A_PARENT_FOR_THIS_CHILD';
  END IF;

  FOR i IN 1..10 LOOP
    v_code := 'INV-' || upper(substr(md5(random()::text || clock_timestamp()::text), 1, 8));
    BEGIN
      INSERT INTO public.child_invites (child_id, code, permission, circle_role, created_by)
      VALUES (p_child_id, v_code, p_permission, p_circle_role, v_uid)
      RETURNING code, expires_at INTO out_code, out_expires_at;
      RETURN NEXT;
      RETURN;
    EXCEPTION WHEN unique_violation THEN
      IF i = 10 THEN RAISE EXCEPTION 'Could not allocate an invite code'; END IF;
    END;
  END LOOP;
END;
$function$

CREATE OR REPLACE FUNCTION public.grant_owner_child_access()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF auth.uid() IS NOT NULL THEN
    INSERT INTO public.child_access (child_id, auth_id, permission, circle_role, invited_by)
    VALUES (NEW.id, auth.uid(), 'full', 'parent', auth.uid())
    ON CONFLICT (child_id, auth_id) DO NOTHING;
  END IF;
  RETURN NEW;
END;
$function$

CREATE OR REPLACE FUNCTION public.lookup_family_by_code(p_code text)
 RETURNS TABLE(out_family_id uuid, out_family_code text)
 LANGUAGE sql
 STABLE SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
  SELECT id, family_code FROM public.families
  WHERE family_code = upper(trim(p_code)) AND is_active = true
  LIMIT 1;
$function$

CREATE OR REPLACE FUNCTION public.prevent_last_parent_removal()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF OLD.circle_role = 'parent' THEN
    IF NOT EXISTS (
      SELECT 1 FROM public.child_access
      WHERE child_id = OLD.child_id AND circle_role = 'parent' AND auth_id <> OLD.auth_id
    ) THEN
      RAISE EXCEPTION 'LAST_PARENT_CANNOT_BE_REMOVED';
    END IF;
  END IF;
  RETURN OLD;
END;
$function$

CREATE OR REPLACE FUNCTION public.provision_current_user(p_full_name text DEFAULT NULL::text, p_role text DEFAULT 'parent'::text, p_join_code text DEFAULT NULL::text, p_child_code text DEFAULT NULL::text)
 RETURNS TABLE(out_family_id uuid, out_family_code text, out_full_name text, out_created boolean, out_joined_child_id uuid, out_joined_child_name text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid     uuid := auth.uid();
  v_email   text;
  v_name    text;
  v_exist   public.users%ROWTYPE;
  v_fam     public.families%ROWTYPE;
  v_code    text;
  v_created boolean := false;
  v_words   text[] := ARRAY['STRONG','BRAVE','CARE','HOPE','LOVE','HEAL','BOND','SAFE'];
  i         int;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'NOT_AUTHENTICATED';
  END IF;

  -- Retired in favor of one-time invite links, which bake in the permission
  -- and circle role the inviting parent chose rather than granting 'full'
  -- access unconditionally. Reject explicitly so a stale cached client gets
  -- a clear reason instead of silently joining a household with no access
  -- to the child it expected.
  IF p_child_code IS NOT NULL AND length(trim(p_child_code)) > 0 THEN
    RAISE EXCEPTION 'LEGACY_CHILD_CODE_DISABLED';
  END IF;

  SELECT email, coalesce(p_full_name, raw_user_meta_data->>'full_name', email)
    INTO v_email, v_name
  FROM auth.users WHERE id = v_uid;

  SELECT * INTO v_exist FROM public.users WHERE auth_id = v_uid;
  IF FOUND THEN
    SELECT * INTO v_fam FROM public.families WHERE id = v_exist.family_id;
    v_name := coalesce(v_exist.full_name, v_name);
  ELSE
    IF p_join_code IS NOT NULL AND length(trim(p_join_code)) > 0 THEN
      SELECT * INTO v_fam FROM public.families
        WHERE family_code = upper(trim(p_join_code)) AND is_active = true;
      IF NOT FOUND THEN
        RAISE EXCEPTION 'INVALID_FAMILY_CODE';
      END IF;
    END IF;

    IF v_fam.id IS NULL THEN
      FOR i IN 1..10 LOOP
        v_code := v_words[1 + floor(random() * array_length(v_words,1))::int]
                  || '-' || lpad((1000 + floor(random()*9000))::int::text, 4, '0');
        BEGIN
          INSERT INTO public.families (family_code, plan) VALUES (v_code, 'beta')
            RETURNING * INTO v_fam;
          EXIT;
        EXCEPTION WHEN unique_violation THEN
          IF i = 10 THEN RAISE EXCEPTION 'Could not allocate a family code'; END IF;
        END;
      END LOOP;
    END IF;

    INSERT INTO public.users (auth_id, family_id, full_name, email, role, is_primary)
    VALUES (v_uid, v_fam.id, v_name, v_email,
            coalesce(p_role, 'parent'),
            (p_join_code IS NULL OR length(trim(p_join_code)) = 0))
    ON CONFLICT (auth_id) DO NOTHING;

    v_created := true;
  END IF;

  RETURN QUERY SELECT v_fam.id, v_fam.family_code, v_name, v_created, NULL::uuid, NULL::text;
END;
$function$

CREATE OR REPLACE FUNCTION public.redeem_child_invite(p_code text, p_full_name text DEFAULT NULL::text)
 RETURNS TABLE(out_family_id uuid, out_family_code text, out_full_name text, out_child_id uuid, out_child_name text, out_permission text, out_circle_role text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid    uuid := auth.uid();
  v_email  text;
  v_name   text;
  v_exist  public.users%ROWTYPE;
  v_fam    public.families%ROWTYPE;
  v_child  public.children%ROWTYPE;
  v_invite public.child_invites%ROWTYPE;
  v_count  int;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'NOT_AUTHENTICATED';
  END IF;

  SELECT * INTO v_invite FROM public.child_invites
    WHERE code = upper(trim(p_code));
  IF NOT FOUND THEN
    RAISE EXCEPTION 'INVALID_INVITE_CODE';
  END IF;
  IF v_invite.revoked_at IS NOT NULL THEN
    RAISE EXCEPTION 'INVITE_REVOKED';
  END IF;
  IF v_invite.used_at IS NOT NULL THEN
    RAISE EXCEPTION 'INVITE_ALREADY_USED';
  END IF;
  IF v_invite.expires_at < now() THEN
    RAISE EXCEPTION 'INVITE_EXPIRED';
  END IF;

  SELECT * INTO v_child FROM public.children WHERE id = v_invite.child_id AND is_active = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'CHILD_NOT_FOUND';
  END IF;

  SELECT email, coalesce(p_full_name, raw_user_meta_data->>'full_name', email)
    INTO v_email, v_name
  FROM auth.users WHERE id = v_uid;

  SELECT * INTO v_exist FROM public.users WHERE auth_id = v_uid;
  IF FOUND THEN
    SELECT * INTO v_fam FROM public.families WHERE id = v_exist.family_id;
    v_name := coalesce(v_exist.full_name, v_name);
  ELSE
    SELECT * INTO v_fam FROM public.families WHERE id = v_child.family_id;
    INSERT INTO public.users (auth_id, family_id, full_name, email, role, is_primary)
    VALUES (v_uid, v_fam.id, v_name, v_email,
            CASE WHEN v_invite.circle_role = 'parent' THEN 'parent' ELSE 'caregiver' END,
            false)
    ON CONFLICT (auth_id) DO NOTHING;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.child_access ca WHERE ca.child_id = v_child.id AND ca.auth_id = v_uid
  ) THEN
    SELECT count(*) INTO v_count FROM public.child_access ca WHERE ca.child_id = v_child.id;
    IF v_count >= 5 THEN
      RAISE EXCEPTION 'CHILD_CAREGIVER_LIMIT';
    END IF;
    INSERT INTO public.child_access (child_id, auth_id, permission, circle_role, invited_by)
    VALUES (v_child.id, v_uid, v_invite.permission, v_invite.circle_role, v_invite.created_by);
  END IF;

  UPDATE public.child_invites SET used_at = now(), used_by = v_uid WHERE id = v_invite.id;

  RETURN QUERY SELECT v_fam.id, v_fam.family_code, v_name, v_child.id, v_child.name,
                      v_invite.permission, v_invite.circle_role;
END;
$function$

CREATE OR REPLACE FUNCTION public.set_child_active_status(p_child_id uuid, p_active boolean)
 RETURNS void
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.child_access ca
    WHERE ca.child_id = p_child_id AND ca.auth_id = auth.uid() AND ca.circle_role = 'parent'
  ) THEN
    RAISE EXCEPTION 'NOT_A_PARENT_FOR_THIS_CHILD';
  END IF;
  UPDATE public.children SET is_active = p_active WHERE id = p_child_id;
END;
$function$

CREATE OR REPLACE FUNCTION public.switch_household(p_join_code text)
 RETURNS TABLE(out_family_id uuid, out_family_code text)
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
DECLARE
  v_uid uuid := auth.uid();
  v_fam public.families%ROWTYPE;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'NOT_AUTHENTICATED';
  END IF;

  IF p_join_code IS NULL OR length(trim(p_join_code)) = 0 THEN
    RAISE EXCEPTION 'INVALID_FAMILY_CODE';
  END IF;

  SELECT * INTO v_fam FROM public.families
    WHERE family_code = upper(trim(p_join_code)) AND is_active = true;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'INVALID_FAMILY_CODE';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM public.users WHERE auth_id = v_uid) THEN
    RAISE EXCEPTION 'NOT_PROVISIONED';
  END IF;

  IF EXISTS (SELECT 1 FROM public.users WHERE auth_id = v_uid AND family_id = v_fam.id) THEN
    RETURN QUERY SELECT v_fam.id, v_fam.family_code;
    RETURN;
  END IF;

  -- The new gate: you must already have been invited to a child in that
  -- household. A correct-but-guessed code is not enough on its own.
  IF NOT EXISTS (
    SELECT 1
    FROM public.child_access ca
    JOIN public.children c ON c.id = ca.child_id
    WHERE ca.auth_id = v_uid AND c.family_id = v_fam.id
  ) THEN
    RAISE EXCEPTION 'NOT_INVITED_TO_THIS_HOUSEHOLD';
  END IF;

  UPDATE public.users SET family_id = v_fam.id, is_primary = false WHERE auth_id = v_uid;

  RETURN QUERY SELECT v_fam.id, v_fam.family_code;
END;
$function$


-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

ALTER TABLE public.child_access ENABLE ROW LEVEL SECURITY;
CREATE POLICY child_access_delete ON public.child_access
  FOR DELETE TO public
  USING (((auth_id = auth.uid()) OR is_parent_of_child(child_id)));
CREATE POLICY child_access_select ON public.child_access
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
ALTER TABLE public.child_invites ENABLE ROW LEVEL SECURITY;
CREATE POLICY child_invites_select ON public.child_invites
  FOR SELECT TO public
  USING ((EXISTS ( SELECT 1
   FROM child_access ca
  WHERE ((ca.child_id = child_invites.child_id) AND (ca.auth_id = auth.uid()) AND (ca.circle_role = 'parent'::text)))));
CREATE POLICY child_invites_update ON public.child_invites
  FOR UPDATE TO public
  USING ((EXISTS ( SELECT 1
   FROM child_access ca
  WHERE ((ca.child_id = child_invites.child_id) AND (ca.auth_id = auth.uid()) AND (ca.circle_role = 'parent'::text)))));
ALTER TABLE public.children ENABLE ROW LEVEL SECURITY;
CREATE POLICY children_delete ON public.children
  FOR DELETE TO public
  USING ((EXISTS ( SELECT 1
   FROM child_access ca
  WHERE ((ca.child_id = children.id) AND (ca.auth_id = auth.uid()) AND (ca.circle_role = 'parent'::text)))));
CREATE POLICY children_insert ON public.children
  FOR INSERT TO public
  WITH CHECK ((family_id IN ( SELECT users.family_id
   FROM users
  WHERE (users.auth_id = auth.uid()))));
CREATE POLICY children_select ON public.children
  FOR SELECT TO public
  USING ((id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY children_update ON public.children
  FOR UPDATE TO public
  USING ((id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.community_posts ENABLE ROW LEVEL SECURITY;
CREATE POLICY family_isolation_community_posts ON public.community_posts
  FOR ALL TO public
  USING ((family_id IN ( SELECT users.family_id
   FROM users
  WHERE (users.auth_id = auth.uid()))));
ALTER TABLE public.contacts ENABLE ROW LEVEL SECURITY;
CREATE POLICY contacts_select ON public.contacts
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY contacts_write ON public.contacts
  FOR ALL TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.doctor_reports ENABLE ROW LEVEL SECURITY;
CREATE POLICY doctor_reports_select ON public.doctor_reports
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY doctor_reports_write ON public.doctor_reports
  FOR ALL TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.families ENABLE ROW LEVEL SECURITY;
CREATE POLICY families_delete ON public.families
  FOR DELETE TO public
  USING ((id IN ( SELECT u.family_id
   FROM users u
  WHERE ((u.auth_id = auth.uid()) AND (u.is_primary = true)))));
CREATE POLICY families_insert ON public.families
  FOR INSERT TO authenticated
  WITH CHECK (true);
CREATE POLICY families_select ON public.families
  FOR SELECT TO public
  USING ((id IN ( SELECT users.family_id
   FROM users
  WHERE (users.auth_id = auth.uid()))));
CREATE POLICY families_update ON public.families
  FOR UPDATE TO public
  USING ((id IN ( SELECT u.family_id
   FROM users u
  WHERE ((u.auth_id = auth.uid()) AND (u.is_primary = true)))))
  WITH CHECK ((id IN ( SELECT u.family_id
   FROM users u
  WHERE ((u.auth_id = auth.uid()) AND (u.is_primary = true)))));
ALTER TABLE public.hydration_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY hydration_logs_select ON public.hydration_logs
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY hydration_logs_write ON public.hydration_logs
  FOR ALL TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.medication_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY medication_logs_select ON public.medication_logs
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY medication_logs_write ON public.medication_logs
  FOR ALL TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.medications ENABLE ROW LEVEL SECURITY;
CREATE POLICY medications_select ON public.medications
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY medications_write ON public.medications
  FOR ALL TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY notes_select ON public.notes
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY notes_write ON public.notes
  FOR ALL TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.pain_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY pain_logs_delete ON public.pain_logs
  FOR DELETE TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
CREATE POLICY pain_logs_insert ON public.pain_logs
  FOR INSERT TO public
  WITH CHECK ((child_id IN ( SELECT report_access_child_ids() AS report_access_child_ids)));
CREATE POLICY pain_logs_select ON public.pain_logs
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY pain_logs_update ON public.pain_logs
  FOR UPDATE TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.quotes ENABLE ROW LEVEL SECURITY;
CREATE POLICY quotes_public_read ON public.quotes
  FOR SELECT TO public
  USING (true);
ALTER TABLE public.subscriptions ENABLE ROW LEVEL SECURITY;
CREATE POLICY family_isolation_subscriptions ON public.subscriptions
  FOR ALL TO public
  USING ((family_id IN ( SELECT users.family_id
   FROM users
  WHERE (users.auth_id = auth.uid()))));
ALTER TABLE public.symptoms ENABLE ROW LEVEL SECURITY;
CREATE POLICY symptoms_select ON public.symptoms
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY symptoms_write ON public.symptoms
  FOR ALL TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.temperature_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY temperature_logs_delete ON public.temperature_logs
  FOR DELETE TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
CREATE POLICY temperature_logs_insert ON public.temperature_logs
  FOR INSERT TO public
  WITH CHECK ((child_id IN ( SELECT report_access_child_ids() AS report_access_child_ids)));
CREATE POLICY temperature_logs_select ON public.temperature_logs
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY temperature_logs_update ON public.temperature_logs
  FOR UPDATE TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
CREATE POLICY users_insert_self ON public.users
  FOR INSERT TO public
  WITH CHECK ((auth_id = auth.uid()));
CREATE POLICY users_select ON public.users
  FOR SELECT TO public
  USING (((auth_id = auth.uid()) OR (auth_id IN ( SELECT ca.auth_id
   FROM child_access ca
  WHERE (ca.child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids))))));
CREATE POLICY users_update_self ON public.users
  FOR UPDATE TO public
  USING ((auth_id = auth.uid()))
  WITH CHECK ((auth_id = auth.uid()));
ALTER TABLE public.weight_logs ENABLE ROW LEVEL SECURITY;
CREATE POLICY weight_logs_select ON public.weight_logs
  FOR SELECT TO public
  USING ((child_id IN ( SELECT accessible_child_ids() AS accessible_child_ids)));
CREATE POLICY weight_logs_write ON public.weight_logs
  FOR ALL TO public
  USING ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)))
  WITH CHECK ((child_id IN ( SELECT full_access_child_ids() AS full_access_child_ids)));
